include ../../ThirdParty/PSCommon/BuildSystem/CommonDefs.mak

BIN_DIR = ../../Bin

SRC_FILES = \
	src/com/primesense/NiteControls/Samples/Boxes/*.java

JAR_NAME = com.primesense.NiteControls.Samples.Boxes
USED_JARS = com.primesense.NiteControls org.openni
MAIN_CLASS = com.primesense.NiteControls.Samples.Boxes.BoxesApplication

include ../../ThirdParty/PSCommon/BuildSystem/CommonJavaMakefile
