include ../../../ThirdParty/PSCommon/BuildSystem/CommonDefs.mak

BIN_DIR = ../../../Bin

SRC_FILES = \
	src/com/primesense/NiteControls/*.java

JAR_NAME = com.primesense.NiteControls
USED_JARS = org.openni

include ../../../ThirdParty/PSCommon/BuildSystem/CommonJavaMakefile

