/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_primesense_NiteControls_NativeMethods */

#ifndef _Included_com_primesense_NiteControls_NativeMethods
#define _Included_com_primesense_NiteControls_NativeMethods
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvBroadcaster_Create
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvBroadcaster_1Create
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvBroadcaster_Destroy
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvBroadcaster_1Destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvMessageGenerator_AddListener
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvMessageGenerator_1AddListener
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvMessageGenerator_RemoveListener
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvMessageGenerator_1RemoveListener
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvMessageGenerator_Generate
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvMessageGenerator_1Generate
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvMessageListener_Update
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvMessageListener_1Update
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvMessageListener_RegisterActivate
 * Signature: (JLjava/lang/Object;Ljava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvMessageListener_1RegisterActivate
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvMessageListener_RegisterDeactivate
 * Signature: (JLjava/lang/Object;Ljava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvMessageListener_1RegisterDeactivate
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvMessageListener_RegisterUpdate
 * Signature: (JLjava/lang/Object;Ljava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvMessageListener_1RegisterUpdate
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvMessageListener_UnregisterActivate
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvMessageListener_1UnregisterActivate
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvMessageListener_UnregisterDeactivate
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvMessageListener_1UnregisterDeactivate
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvMessageListener_UnregisterUpdate
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvMessageListener_1UnregisterUpdate
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvFlowRouter_Create
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvFlowRouter_1Create
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvFlowRouter_Destroy
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvFlowRouter_1Destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvFlowRouter_SetActive
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvFlowRouter_1SetActive
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvFlowRouter_GetActive
 * Signature: (JLorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvFlowRouter_1GetActive
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvPointControl_Create
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvPointControl_1Create
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvPointControl_Destroy
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvPointControl_1Destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvPointControl_RegisterPointCreate
 * Signature: (JLjava/lang/Object;Ljava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvPointControl_1RegisterPointCreate
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvPointControl_RegisterPointUpdate
 * Signature: (JLjava/lang/Object;Ljava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvPointControl_1RegisterPointUpdate
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvPointControl_RegisterPointDestroy
 * Signature: (JLjava/lang/Object;Ljava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvPointControl_1RegisterPointDestroy
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvPointControl_RegisterPrimaryPointCreate
 * Signature: (JLjava/lang/Object;Ljava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvPointControl_1RegisterPrimaryPointCreate
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvPointControl_RegisterPrimaryPointUpdate
 * Signature: (JLjava/lang/Object;Ljava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvPointControl_1RegisterPrimaryPointUpdate
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvPointControl_RegisterPrimaryPointReplace
 * Signature: (JLjava/lang/Object;Ljava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvPointControl_1RegisterPrimaryPointReplace
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvPointControl_RegisterPrimaryPointDestroy
 * Signature: (JLjava/lang/Object;Ljava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvPointControl_1RegisterPrimaryPointDestroy
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvPointControl_RegisterNoPoints
 * Signature: (JLjava/lang/Object;Ljava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvPointControl_1RegisterNoPoints
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvPointControl_UnregisterPointCreate
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvPointControl_1UnregisterPointCreate
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvPointControl_UnregisterPointUpdate
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvPointControl_1UnregisterPointUpdate
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvPointControl_UnregisterPointDestroy
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvPointControl_1UnregisterPointDestroy
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvPointControl_UnregisterPrimaryPointCreate
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvPointControl_1UnregisterPrimaryPointCreate
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvPointControl_UnregisterPrimaryPointUpdate
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvPointControl_1UnregisterPrimaryPointUpdate
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvPointControl_UnregisterPrimaryPointReplace
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvPointControl_1UnregisterPrimaryPointReplace
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvPointControl_UnregisterPrimaryPointDestroy
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvPointControl_1UnregisterPrimaryPointDestroy
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvPointControl_UnregisterNoPoints
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvPointControl_1UnregisterNoPoints
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvPointControl_GetPrimaryID
 * Signature: (JLorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvPointControl_1GetPrimaryID
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvPushDetector_Create
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvPushDetector_1Create
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvPushDetector_Destroy
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvPushDetector_1Destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvPushDetector_RegisterPush
 * Signature: (JLjava/lang/Object;Ljava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvPushDetector_1RegisterPush
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvPushDetector_RegisterStabilized
 * Signature: (JLjava/lang/Object;Ljava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvPushDetector_1RegisterStabilized
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvPushDetector_UnregisterPush
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvPushDetector_1UnregisterPush
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvPushDetector_UnregisterStabilized
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvPushDetector_1UnregisterStabilized
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvPushDetector_Reset
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvPushDetector_1Reset
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvPushDetector_SetPushImmediateMinimumVelocity
 * Signature: (JF)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvPushDetector_1SetPushImmediateMinimumVelocity
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvPushDetector_SetPushImmediateDuration
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvPushDetector_1SetPushImmediateDuration
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvPushDetector_SetPushImmediateOffset
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvPushDetector_1SetPushImmediateOffset
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvPushDetector_SetPushPreviousMinimumVelocity
 * Signature: (JF)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvPushDetector_1SetPushPreviousMinimumVelocity
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvPushDetector_SetPushPreviousDuration
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvPushDetector_1SetPushPreviousDuration
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvPushDetector_SetPushPreviousOffset
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvPushDetector_1SetPushPreviousOffset
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvPushDetector_SetPushMaximumAngleBetweenImmediateAndZ
 * Signature: (JF)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvPushDetector_1SetPushMaximumAngleBetweenImmediateAndZ
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvPushDetector_SetPushMinimumAngleBetweenImmediateAndPrevious
 * Signature: (JF)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvPushDetector_1SetPushMinimumAngleBetweenImmediateAndPrevious
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvPushDetector_SetStableMaximumVelocity
 * Signature: (JF)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvPushDetector_1SetStableMaximumVelocity
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvPushDetector_SetStableDuration
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvPushDetector_1SetStableDuration
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvPushDetector_GetPushImmediateMinimumVelocity
 * Signature: (JLorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvPushDetector_1GetPushImmediateMinimumVelocity
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvPushDetector_GetPushImmediateDuration
 * Signature: (JLorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvPushDetector_1GetPushImmediateDuration
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvPushDetector_GetPushImmediateOffset
 * Signature: (JLorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvPushDetector_1GetPushImmediateOffset
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvPushDetector_GetPushPreviousMinimumVelocity
 * Signature: (JLorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvPushDetector_1GetPushPreviousMinimumVelocity
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvPushDetector_GetPushPreviousDuration
 * Signature: (JLorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvPushDetector_1GetPushPreviousDuration
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvPushDetector_GetPushPreviousOffset
 * Signature: (JLorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvPushDetector_1GetPushPreviousOffset
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvPushDetector_GetPushMaximumAngleBetweenImmediateAndZ
 * Signature: (JLorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvPushDetector_1GetPushMaximumAngleBetweenImmediateAndZ
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvPushDetector_GetPushMinimumAngleBetweenImmediateAndPrevious
 * Signature: (JLorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvPushDetector_1GetPushMinimumAngleBetweenImmediateAndPrevious
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvPushDetector_GetStableMaximumVelocity
 * Signature: (JLorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvPushDetector_1GetStableMaximumVelocity
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvPushDetector_GetStableDuration
 * Signature: (JLorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvPushDetector_1GetStableDuration
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSelectableSlider1D_Create
 * Signature: (IIZFFLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSelectableSlider1D_1Create
  (JNIEnv *, jclass, jint, jint, jboolean, jfloat, jfloat, jstring);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSelectableSlider1D_Destroy
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSelectableSlider1D_1Destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSelectableSlider1D_Reposition
 * Signature: (JFFF)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSelectableSlider1D_1Reposition
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSelectableSlider1D_GetCenter
 * Signature: (JLorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSelectableSlider1D_1GetCenter
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSelectableSlider1D_RegisterItemHover
 * Signature: (JLjava/lang/Object;Ljava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSelectableSlider1D_1RegisterItemHover
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSelectableSlider1D_RegisterItemSelect
 * Signature: (JLjava/lang/Object;Ljava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSelectableSlider1D_1RegisterItemSelect
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSelectableSlider1D_RegisterValueChange
 * Signature: (JLjava/lang/Object;Ljava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSelectableSlider1D_1RegisterValueChange
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSelectableSlider1D_RegisterOffAxisMovement
 * Signature: (JLjava/lang/Object;Ljava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSelectableSlider1D_1RegisterOffAxisMovement
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSelectableSlider1D_UnregisterItemHover
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSelectableSlider1D_1UnregisterItemHover
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSelectableSlider1D_UnregisterItemSelect
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSelectableSlider1D_1UnregisterItemSelect
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSelectableSlider1D_UnregisterValueChange
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSelectableSlider1D_1UnregisterValueChange
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSelectableSlider1D_UnregisterOffAxisMovement
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSelectableSlider1D_1UnregisterOffAxisMovement
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSelectableSlider1D_SetItemCount
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSelectableSlider1D_1SetItemCount
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSelectableSlider1D_GetItemCount
 * Signature: (JLorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSelectableSlider1D_1GetItemCount
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSelectableSlider1D_SetSliderSize
 * Signature: (JF)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSelectableSlider1D_1SetSliderSize
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSelectableSlider1D_GetSliderSize
 * Signature: (JLorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSelectableSlider1D_1GetSliderSize
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSelectableSlider1D_SetValueChangeOnOffAxis
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSelectableSlider1D_1SetValueChangeOnOffAxis
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSelectableSlider1D_GetValueChangeOnOffAxis
 * Signature: (JLorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSelectableSlider1D_1GetValueChangeOnOffAxis
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSelectableSlider2D_Create
 * Signature: (IIFFLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSelectableSlider2D_1Create
  (JNIEnv *, jclass, jint, jint, jfloat, jfloat, jstring);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSelectableSlider2D_Destroy
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSelectableSlider2D_1Destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSelectableSlider2D_Reposition
 * Signature: (JFFF)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSelectableSlider2D_1Reposition
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSelectableSlider2D_GetCenter
 * Signature: (JLorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSelectableSlider2D_1GetCenter
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSelectableSlider2D_RegisterItemHover
 * Signature: (JLjava/lang/Object;Ljava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSelectableSlider2D_1RegisterItemHover
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSelectableSlider2D_RegisterItemSelect
 * Signature: (JLjava/lang/Object;Ljava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSelectableSlider2D_1RegisterItemSelect
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSelectableSlider2D_RegisterValueChange
 * Signature: (JLjava/lang/Object;Ljava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSelectableSlider2D_1RegisterValueChange
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSelectableSlider2D_RegisterOffAxisMovement
 * Signature: (JLjava/lang/Object;Ljava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSelectableSlider2D_1RegisterOffAxisMovement
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSelectableSlider2D_UnregisterItemHover
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSelectableSlider2D_1UnregisterItemHover
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSelectableSlider2D_UnregisterItemSelect
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSelectableSlider2D_1UnregisterItemSelect
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSelectableSlider2D_UnregisterValueChange
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSelectableSlider2D_1UnregisterValueChange
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSelectableSlider2D_UnregisterOffAxisMovement
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSelectableSlider2D_1UnregisterOffAxisMovement
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSelectableSlider2D_GetItemXCount
 * Signature: (JLorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSelectableSlider2D_1GetItemXCount
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSelectableSlider2D_SetItemXCount
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSelectableSlider2D_1SetItemXCount
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSelectableSlider2D_GetItemYCount
 * Signature: (JLorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSelectableSlider2D_1GetItemYCount
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSelectableSlider2D_SetItemYCount
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSelectableSlider2D_1SetItemYCount
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSelectableSlider2D_GetSliderXSize
 * Signature: (JLorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSelectableSlider2D_1GetSliderXSize
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSelectableSlider2D_GetSliderYSize
 * Signature: (JLorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSelectableSlider2D_1GetSliderYSize
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSelectableSlider2D_SetSliderSize
 * Signature: (JFF)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSelectableSlider2D_1SetSliderSize
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSelectableSlider2D_GetValueChangeOnOffAxis
 * Signature: (JLorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSelectableSlider2D_1GetValueChangeOnOffAxis
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSelectableSlider2D_SetValueChangeOnOffAxis
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSelectableSlider2D_1SetValueChangeOnOffAxis
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSessionManager_Create
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSessionManager_1Create
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSessionManager_Destroy
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSessionManager_1Destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSessionManager_Initialize
 * Signature: (JJLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSessionManager_1Initialize
  (JNIEnv *, jclass, jlong, jlong, jstring);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSessionManager_Update
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSessionManager_1Update
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSessionManager_AddGestureByContext
 * Signature: (JJLjava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSessionManager_1AddGestureByContext
  (JNIEnv *, jclass, jlong, jlong, jstring, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSessionManager_RemoveGesture
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSessionManager_1RemoveGesture
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSessionGenerator_RegisterToSessionStart
 * Signature: (JLjava/lang/Object;Ljava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSessionGenerator_1RegisterToSessionStart
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSessionGenerator_RegisterToSessionEnd
 * Signature: (JLjava/lang/Object;Ljava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSessionGenerator_1RegisterToSessionEnd
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSessionGenerator_RegisterToSessionFocusProgress
 * Signature: (JLjava/lang/Object;Ljava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSessionGenerator_1RegisterToSessionFocusProgress
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSessionGenerator_UnregisterFromSessionStart
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSessionGenerator_1UnregisterFromSessionStart
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSessionGenerator_UnregisterFromSessionEnd
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSessionGenerator_1UnregisterFromSessionEnd
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSessionGenerator_UnregisterFromSessionFocusProgress
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSessionGenerator_1UnregisterFromSessionFocusProgress
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSessionGenerator_LosePoint
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSessionGenerator_1LosePoint
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSessionGenerator_LosePoints
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSessionGenerator_1LosePoints
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSessionGenerator_EndSession
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSessionGenerator_1EndSession
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSessionGenerator_ForceSession
 * Signature: (JFFF)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSessionGenerator_1ForceSession
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSessionGenerator_TrackPoint
 * Signature: (JFFF)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSessionGenerator_1TrackPoint
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSessionGenerator_IsInSession
 * Signature: (JLorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSessionGenerator_1IsInSession
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSessionGenerator_GetFocusPoint
 * Signature: (JLorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSessionGenerator_1GetFocusPoint
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSteadyDetector_Create
 * Signature: (IIFLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSteadyDetector_1Create
  (JNIEnv *, jclass, jint, jint, jfloat, jstring);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSteadyDetector_Destroy
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSteadyDetector_1Destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSteadyDetector_RegisterSteady
 * Signature: (JLjava/lang/Object;Ljava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSteadyDetector_1RegisterSteady
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSteadyDetector_RegisterNotSteady
 * Signature: (JLjava/lang/Object;Ljava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSteadyDetector_1RegisterNotSteady
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSteadyDetector_UnregisterSteady
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSteadyDetector_1UnregisterSteady
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSteadyDetector_UnregisterNotSteady
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSteadyDetector_1UnregisterNotSteady
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSteadyDetector_Reset
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSteadyDetector_1Reset
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSteadyDetector_GetDetectionDuration
 * Signature: (JLorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSteadyDetector_1GetDetectionDuration
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSteadyDetector_GetMaximumStdDevForSteady
 * Signature: (JLorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSteadyDetector_1GetMaximumStdDevForSteady
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSteadyDetector_GetMinimumStdDevForNotSteady
 * Signature: (JLorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSteadyDetector_1GetMinimumStdDevForNotSteady
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSteadyDetector_SetMaximumStdDevForSteady
 * Signature: (JF)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSteadyDetector_1SetMaximumStdDevForSteady
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSteadyDetector_SetMinimumStdDevForNotSteady
 * Signature: (JF)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSteadyDetector_1SetMinimumStdDevForNotSteady
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSteadyDetector_SetDetectionDuration
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSteadyDetector_1SetDetectionDuration
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSwipeDetector_Create
 * Signature: (ZLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSwipeDetector_1Create
  (JNIEnv *, jclass, jboolean, jstring);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSwipeDetector_Destroy
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSwipeDetector_1Destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSwipeDetector_Reset
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSwipeDetector_1Reset
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSwipeDetector_RegisterSwipeUp
 * Signature: (JLjava/lang/Object;Ljava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSwipeDetector_1RegisterSwipeUp
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSwipeDetector_RegisterSwipeDown
 * Signature: (JLjava/lang/Object;Ljava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSwipeDetector_1RegisterSwipeDown
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSwipeDetector_RegisterSwipeLeft
 * Signature: (JLjava/lang/Object;Ljava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSwipeDetector_1RegisterSwipeLeft
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSwipeDetector_RegisterSwipeRight
 * Signature: (JLjava/lang/Object;Ljava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSwipeDetector_1RegisterSwipeRight
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSwipeDetector_RegisterGeneralSwipe
 * Signature: (JLjava/lang/Object;Ljava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSwipeDetector_1RegisterGeneralSwipe
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSwipeDetector_UnregisterSwipeUp
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSwipeDetector_1UnregisterSwipeUp
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSwipeDetector_UnregisterSwipeDown
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSwipeDetector_1UnregisterSwipeDown
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSwipeDetector_UnregisterSwipeLeft
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSwipeDetector_1UnregisterSwipeLeft
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSwipeDetector_UnregisterSwipeRight
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSwipeDetector_1UnregisterSwipeRight
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSwipeDetector_UnregisterGeneralSwipe
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSwipeDetector_1UnregisterGeneralSwipe
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSwipeDetector_SetMotionSpeedThreshold
 * Signature: (JF)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSwipeDetector_1SetMotionSpeedThreshold
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSwipeDetector_SetMotionTime
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSwipeDetector_1SetMotionTime
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSwipeDetector_SetXAngleThreshold
 * Signature: (JF)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSwipeDetector_1SetXAngleThreshold
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSwipeDetector_SetYAngleThreshold
 * Signature: (JF)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSwipeDetector_1SetYAngleThreshold
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSwipeDetector_SetSteadyMaxStdDev
 * Signature: (JF)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSwipeDetector_1SetSteadyMaxStdDev
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSwipeDetector_SetSteadyDuration
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSwipeDetector_1SetSteadyDuration
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSwipeDetector_SetUseSteady
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSwipeDetector_1SetUseSteady
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSwipeDetector_GetMotionSpeedThreshold
 * Signature: (JLorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSwipeDetector_1GetMotionSpeedThreshold
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSwipeDetector_GetMotionTime
 * Signature: (JLorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSwipeDetector_1GetMotionTime
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSwipeDetector_GetXAngleThreshold
 * Signature: (JLorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSwipeDetector_1GetXAngleThreshold
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSwipeDetector_GetYAngleThreshold
 * Signature: (JLorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSwipeDetector_1GetYAngleThreshold
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSwipeDetector_GetSteadyMaxStdDev
 * Signature: (JLorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSwipeDetector_1GetSteadyMaxStdDev
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSwipeDetector_GetSteadyDuration
 * Signature: (JLorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSwipeDetector_1GetSteadyDuration
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvSwipeDetector_GetUseSteady
 * Signature: (JLorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvSwipeDetector_1GetUseSteady
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvPointFilter_Create
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvPointFilter_1Create
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvPointFilter_Destroy
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvPointFilter_1Destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvPointFilter_OverridePrimary
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvPointFilter_1OverridePrimary
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvPointArea_Create
 * Signature: (FFFFFFZLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvPointArea_1Create
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jboolean, jstring);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvPointArea_Destroy
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvPointArea_1Destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvPointArea_ChangeArea
 * Signature: (JFFFFFFZ)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvPointArea_1ChangeArea
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jboolean);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvPointArea_RemoveSilent
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvPointArea_1RemoveSilent
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvPointArea_RegisterPointSilenced
 * Signature: (JLjava/lang/Object;Ljava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvPointArea_1RegisterPointSilenced
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvPointArea_RegisterPointRevived
 * Signature: (JLjava/lang/Object;Ljava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvPointArea_1RegisterPointRevived
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvPointArea_RegisterSilentPointRemoved
 * Signature: (JLjava/lang/Object;Ljava/lang/String;Lorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvPointArea_1RegisterSilentPointRemoved
  (JNIEnv *, jclass, jlong, jobject, jstring, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvPointArea_UnregisterPointSilenced
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvPointArea_1UnregisterPointSilenced
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvPointArea_UnregisterPointRevived
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvPointArea_1UnregisterPointRevived
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvPointArea_UnregisterSilentPointRemoved
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvPointArea_1UnregisterSilentPointRemoved
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvPointDenoiser_Create
 * Signature: (FLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvPointDenoiser_1Create
  (JNIEnv *, jclass, jfloat, jstring);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvPointDenoiser_Destroy
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvPointDenoiser_1Destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvPointDenoiser_SetDistanceThreshold
 * Signature: (JF)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvPointDenoiser_1SetDistanceThreshold
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvPointDenoiser_GetDistanceThreshold
 * Signature: (JLorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvPointDenoiser_1GetDistanceThreshold
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvPointDenoiser_SetCloseRatio
 * Signature: (JF)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvPointDenoiser_1SetCloseRatio
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvPointDenoiser_GetCloseRatio
 * Signature: (JLorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvPointDenoiser_1GetCloseRatio
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvPointDenoiser_SetFarRatio
 * Signature: (JF)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvPointDenoiser_1SetFarRatio
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     com_primesense_NiteControls_NativeMethods
 * Method:    xnvPointDenoiser_GetFarRatio
 * Signature: (JLorg/openni/OutArg;)I
 */
JNIEXPORT jint JNICALL Java_com_primesense_NiteControls_NativeMethods_xnvPointDenoiser_1GetFarRatio
  (JNIEnv *, jclass, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
